name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - 'jb/cloudflare-hosting'
  workflow_run:
    workflows: ["Pull Request"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Emscripten release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download fheroes2-emscripten-sdl2_dev -D ./dist

      - name: Extract ZIP file
        run: |
          cd dist
          unzip fheroes2_emscripten.zip -d extracted
          mv extracted/* .
          rm -rf extracted fheroes2_emscripten.zip

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy ./dist --project-name fheroes2-online
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
