name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ["Make"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fheroes2_emscripten.zip
          path: ./dist

      - name: Extract ZIP file
        run: |
          cd dist
          unzip fheroes2_emscripten.zip -d extracted
          mv extracted/* .
          rm -rf extracted fheroes2_emscripten.zip

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy ./dist --project-name fheroes2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
